: Copy Files of Borland Turbo C++4.0J to the root directory.
@echo off

: for %1 in (c4j-inc\ALLOC.H, c4j-inc\_NULL.H) do copy %1 .

cd c4j-include

copy ALLOC.H ..
copy ASSERT.H ..
copy BCD.H ..
copy BIDSC.LIB ..
copy BIDSH.LIB ..
copy BIDSL.LIB ..
copy BIDSM.LIB ..
copy BIDSS.LIB ..
copy BIOS.H ..
copy C0C.OBJ ..
copy C0FC.OBJ ..
copy C0FH.OBJ ..
copy C0FL.OBJ ..
copy C0FM.OBJ ..
copy C0FS.OBJ ..
copy C0FT.OBJ ..
copy C0H.OBJ ..
copy C0L.OBJ ..
copy C0M.OBJ ..
copy C0S.OBJ ..
copy C0T.OBJ ..
copy CC.LIB ..
copy CH.LIB ..
copy CHECKS.H ..
copy CL.LIB ..
copy CM.LIB ..
copy COMPLEX.H ..
copy CONIO.H ..
copy CONIOIBM.LIB ..
copy CONIONEC.LIB ..
copy CONSTREA.H ..
copy CS.LIB ..
copy CSTRING.H ..
copy CT.LIB ..
copy CTYPE.H ..
copy DIR.H ..
copy DIRECT.H ..
copy DIRENT.H ..
copy DOS.H ..
copy DOSV.H ..
copy EMU.LIB ..
copy EMUIBM.OBJ ..
copy EMUNEC.OBJ ..
copy ERRNO.H ..
copy EXCEPT.H ..
copy FCNTL.H ..
copy FLOAT.H ..
copy FP87.LIB ..
copy FP87IBM.OBJ ..
copy FP87NEC.OBJ ..
copy FSTREAM.H ..
copy GENERIC.H ..
copy GRAPHICS.H ..
copy GRAPHICS.LIB ..
copy IO.H ..
copy IOMANIP.H ..
copy IOSTREAM.H ..
copy JCTYPE.H ..
copy JSTRING.H ..
copy LIMITS.H ..
copy LOCALE.H ..
copy MALLOC.H ..
copy MATH.H ..
copy MATHC.LIB ..
copy MATHH.LIB ..
copy MATHL.LIB ..
copy MATHM.LIB ..
copy MATHS.LIB ..
copy MBCTYPE.H ..
copy MBSTRING.H ..
copy MEM.H ..
copy MEMORY.H ..
copy NEW.H ..
copy NOEHC.LIB ..
copy NOEHH.LIB ..
copy NOEHL.LIB ..
copy NOEHM.LIB ..
copy NOEHS.LIB ..
copy OBSOLETE.LIB ..
copy OVERLAY.LIB ..
copy OVLYIBM.LIB ..
copy OVLYNEC.LIB ..
copy PROCESS.H ..
copy REF.H ..
copy REGEXP.H ..
copy SEARCH.H ..
copy SETJMP.H ..
copy SHARE.H ..
copy SIGNAL.H ..
copy STDARG.H ..
copy STDDEF.H ..
copy STDIO.H ..
copy STDIOSTR.H ..
copy STDLIB.H ..
copy STRING.H ..
copy STRSTREA.H ..
copy SYSTYPES.H ..
copy TIME.H ..
copy TYPEINFO.H ..
copy UTIME.H ..
copy VALUES.H ..
copy VARARGS.H ..
copy _DEFS.H ..
copy _NFILE.H ..
copy _NULL.H ..

cd ..